# Generated by Django 5.0.7 on 2026-09-22 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed')], default='running', max_length=20)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=20)),
                ('batch_size', models.PositiveIntegerField(default=40)),
                ('backlog_pause_threshold', models.PositiveIntegerField(default=300)),
                ('backlog_resume_threshold', models.PositiveIntegerField(default=230)),
                ('pause_duration_minutes', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
