# Generated by Django 5.0.7 on 2026-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crawlsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='unique_running_crawl_session'),
        ),
    ]
