# Generated by Django 5.0.7 on 2026-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_sessions', '0002_crawlsession_unique_running_crawl_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlsession',
            name='backlog_pause_threshold',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
