# Generated by Django 5.0.7 on 2026-09-22 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawl_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shine_profile_url', models.URLField(max_length=1000)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_text', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('search_term', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField()),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='crawl_sessions.crawlsession')),
            ],
            options={
                'ordering': ['extracted_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='candidates__session_85df74_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='candidaterecord',
            constraint=models.UniqueConstraint(fields=('session', 'shine_profile_url'), name='unique_candidate_per_session'),
        ),
    ]
