# Generated by Django 5.0.7 on 2026-09-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidaterecord_results_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterecord',
            name='elements_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidaterecord',
            name='files_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidaterecord',
            name='images_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
