# Generated by Django 5.0.7 on 2026-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidaterecord_elements_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterecord',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('success', 'Success'), ('failed', 'Failed'), ('already_extracted', 'Already Extracted')], default='queued', max_length=20),
        ),
    ]
